formatter:
  trailing_commas: preserve

analyzer:
  errors:
    non_constant_identifier_names: ignore
include: package:lints/recommended.yaml

linter:
  rules:
    always_use_package_imports: true
    prefer_relative_imports: false
    directives_ordering: true
    file_names: false
    unnecessary_string_interpolations: false