name: cptclient
description: Course Participation Tracker

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.5.0-alpha2+8

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: 3.35.3

dependencies:

  # Flutter
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  diacritic: 0.1.6

  # Fetch data from the internet
  http: 1.5.0

  # Hash the password
  crypto: 3.0.6

  # Date & Time
  intl: 0.20.2

  # Local storage
  shared_preferences: 2.5.3

  # Global storage (yaml)
  yaml: 3.1.3

  # More icons
  cupertino_icons: 1.0.8

  # Dynamic routes
  go_router: 16.2.1

  # QR codes
  qr_flutter: 4.1.0
  screenshot: 3.0.0

  # Save dialog
  file_selector: 1.0.3

  # Clickable URL
  url_launcher: 6.3.2

  # CSV export
  csv: 6.0.0

  # PDF export
  pdf: 3.11.3

dev_dependencies:
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  # Custom localization
  generate: true

  # Material Icons font
  uses-material-design: true

  # Local assets
  assets:
    - cptclient.yaml
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/SourceSansPro/source-sans-pro.regular.ttf
    - assets/fonts/SourceSansPro/source-sans-pro.bold.ttf
    - assets/fonts/SourceSansPro/source-sans-pro.italic.ttf
    - assets/fonts/SourceSansPro/source-sans-pro.bold-italic.ttf

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_cpt_256.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
