name: cptclient
description: Course Participation Tracker

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 0.9.0+1

environment:
  sdk: '>=3.0.0'

dependencies:

  # Flutter
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  diacritic: ^0.1.5

  # Fetch data from the internet
  http: ^1.2.0

  # Hash the password
  crypto: ^3.0.0

  # Date & Time
  intl: any

  # Local Storage
  universal_html: ^2.2.4

  # Global storage (yaml)
  yaml: any

  # More icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  # Custom localization
  generate: true

  # Material Icons font
  uses-material-design: true

  # Local assets
  assets:
    - cptclient.yaml
    - assets/
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_cpt_256.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
