name: build-release

on:
  workflow_call:
    inputs:
      flutter_version:
        required: false
        default: '3.35.3'
        type: string
      upload_action_artifact:
        description: 'Upload build artifacts in the GH action'
        required: false
        default: true
        type: boolean
      upload_pages_artifact:
        description: 'Upload build artifact to GH pages'
        required: false
        default: false
        type: boolean
      upload_release_artifact:
        description: 'Upload build artifact to GH release'
        required: false
        default: false
        type: boolean

jobs:
  build-artifacts:
    name: Release Client as ${{ matrix.build-type }} (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}

    env:
      APP_NAME: cptclient
      SERVER_SCHEME: https
      SERVER_HOST: cptserver.oberhauser.dev
      SERVER_PORT: 443
      ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: web
            build-type: web
            asset: web.tar.gz
          - os: ubuntu-latest
            platform: linux
            build-type: linux
            asset: linux-amd64.tar.gz
          - os: ubuntu-latest
            platform: android
            build-type: apk
            asset: android.apk
          - os: windows-latest
            platform: windows
            build-type: windows
            asset: windows-amd64.zip
          - os: macos-14
            platform: macos
            build-type: macos
            asset: macos-arm64.tar.gz

    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: 'stable'
      - name: Create Default Config File
        run: cp cptclient-template.yaml cptclient.yaml
      - uses: actions/setup-java@v5
        if: matrix.platform == 'android'
        with:
          # AGP8 needs JDK 17
          distribution: 'temurin'
          java-version: '17'
      - name: Install Linux Dependencies
        if: matrix.platform == 'linux'
        # Install libunwind-dev, see https://github.com/actions/runner-images/issues/6399#issuecomment-1285011525
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          sudo apt-get install -y libunwind-dev
      - name: Install current bash on macOS
        shell: bash
        if: runner.os == 'macos'
        run: |
          brew install bash
          bash --version
      - name: Install zip on windows
        if: matrix.platform == 'windows'
        run: choco install zip -y
      - name: Build App
        id: build
        shell: bash
        run: ./release.sh ${{ matrix.build-type }} ${{ matrix.build-type }}
      - name: Upload build artifact to the GH action
        if: inputs.upload_action_artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ github.ref_name }}-${{ matrix.asset }}
          path: release/${{ env.APP_NAME }}-${{ matrix.asset }}
      - name: Upload artifacts to GH pages
        if: inputs.upload_pages_artifact && matrix.platform == 'web'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web
      - name: Upload artifacts to GH release
        if: inputs.upload_release_artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: release/${{ env.APP_NAME }}-${{ matrix.asset }}
          asset_name: "${{ env.APP_NAME }}-${{ github.ref_name }}-${{ matrix.asset }}"
          tag: ${{ github.ref }}

  deploy-github-pages:
    if: inputs.upload_pages_artifact
    needs:
      - build-artifacts
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4