name: on-pull-request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  call-test:
    uses: ./.github/workflows/test.yml
  call-build-client:
    needs:
      - call-test
    uses: ./.github/workflows/build-dev.yml
